const encoder = new TextEncoder();

interface ZipEntry {
  name: string;
  bytes: Uint8Array;
}

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ ((crc & 1) ? 0xedb88320 : 0);
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function pushU16(target: number[], value: number): void {
  target.push(value & 0xff, (value >>> 8) & 0xff);
}

function pushU32(target: number[], value: number): void {
  target.push(
    value & 0xff,
    (value >>> 8) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 24) & 0xff,
  );
}

function pushBytes(target: number[], bytes: Uint8Array): void {
  for (const byte of bytes) target.push(byte);
}

function createStoredZip(entries: readonly ZipEntry[]): Uint8Array {
  const output: number[] = [];
  const central: number[] = [];
  let offset = 0;

  for (const entry of entries) {
    const name = encoder.encode(entry.name);
    const checksum = crc32(entry.bytes);
    const local: number[] = [];
    pushU32(local, 0x04034b50);
    pushU16(local, 20);
    pushU16(local, 0);
    pushU16(local, 0);
    pushU16(local, 0);
    pushU16(local, 0);
    pushU32(local, checksum);
    pushU32(local, entry.bytes.length);
    pushU32(local, entry.bytes.length);
    pushU16(local, name.length);
    pushU16(local, 0);
    pushBytes(local, name);
    pushBytes(local, entry.bytes);
    pushBytes(output, Uint8Array.from(local));

    pushU32(central, 0x02014b50);
    pushU16(central, 20);
    pushU16(central, 20);
    pushU16(central, 0);
    pushU16(central, 0);
    pushU16(central, 0);
    pushU16(central, 0);
    pushU32(central, checksum);
    pushU32(central, entry.bytes.length);
    pushU32(central, entry.bytes.length);
    pushU16(central, name.length);
    pushU16(central, 0);
    pushU16(central, 0);
    pushU16(central, 0);
    pushU16(central, 0);
    pushU32(central, 0);
    pushU32(central, offset);
    pushBytes(central, name);

    offset += local.length;
  }

  const centralOffset = output.length;
  pushBytes(output, Uint8Array.from(central));
  const end: number[] = [];
  pushU32(end, 0x06054b50);
  pushU16(end, 0);
  pushU16(end, 0);
  pushU16(end, entries.length);
  pushU16(end, entries.length);
  pushU32(end, central.length);
  pushU32(end, centralOffset);
  pushU16(end, 0);
  pushBytes(output, Uint8Array.from(end));
  return Uint8Array.from(output);
}

function run(text: string, options: { bold?: boolean; size?: number; color?: string } = {}): string {
  const properties = [
    options.bold ? '<w:b/>' : '',
    options.size ? `<w:sz w:val="${options.size}"/><w:szCs w:val="${options.size}"/>` : '',
    options.color ? `<w:color w:val="${options.color}"/>` : '',
  ].join('');
  return `<w:r>${properties ? `<w:rPr>${properties}</w:rPr>` : ''}<w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r>`;
}

function paragraph(
  content: string,
  options: { bold?: boolean; size?: number; color?: string; align?: 'center' | 'left'; before?: number; after?: number } = {},
): string {
  const pPr = [
    options.align ? `<w:jc w:val="${options.align}"/>` : '',
    options.before !== undefined || options.after !== undefined
      ? `<w:spacing w:before="${options.before ?? 0}" w:after="${options.after ?? 0}"/>`
      : '',
  ].join('');
  return `<w:p>${pPr ? `<w:pPr>${pPr}</w:pPr>` : ''}${run(content, options)}</w:p>`;
}

function summaryRow(label: string, value: string): string {
  return [
    '<w:tr>',
    '<w:tc><w:tcPr><w:tcW w:w="2200" w:type="dxa"/></w:tcPr>',
    paragraph(label, { bold: true, color: '243B53', after: 30 }),
    '</w:tc>',
    '<w:tc><w:tcPr><w:tcW w:w="6800" w:type="dxa"/></w:tcPr>',
    paragraph(value, { after: 30 }),
    '</w:tc>',
    '</w:tr>',
  ].join('');
}

function documentXml(): string {
  const body = [
    paragraph('VERIREMIT', { bold: true, size: 36, color: '102A43', align: 'center', after: 60 }),
    paragraph('Payment Release Authorization', { bold: true, size: 28, align: 'center', after: 40 }),
    paragraph('Human-verified vendor payment change · generated by Doctavian', { size: 18, color: '486581', align: 'center', after: 220 }),
    '<w:tbl><w:tblPr><w:tblW w:w="9000" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="BCCCDC"/><w:left w:val="single" w:sz="4" w:color="BCCCDC"/><w:bottom w:val="single" w:sz="4" w:color="BCCCDC"/><w:right w:val="single" w:sz="4" w:color="BCCCDC"/><w:insideH w:val="single" w:sz="4" w:color="D9E2EC"/><w:insideV w:val="single" w:sz="4" w:color="D9E2EC"/></w:tblBorders></w:tblPr>',
    summaryRow('Case', '{!Release.CaseId}'),
    summaryRow('Supplier', '{!Release.Supplier}'),
    summaryRow('Vendor ID', '{!Release.VendorId}'),
    summaryRow('Purchase order', '{!Release.PoNumber}'),
    summaryRow('Amount', '{!Release.Amount} {!Release.Currency}'),
    summaryRow('Beneficiary', '{!Release.Beneficiary}'),
    summaryRow('Verified IBAN', '{!Release.Iban}'),
    '</w:tbl>',
    paragraph('Independent human verification', { bold: true, size: 24, color: '102A43', before: 240, after: 80 }),
    paragraph('Reviewer: {!Release.ReviewerName}', { after: 40 }),
    paragraph('Reference: {!Release.VerificationReference}', { after: 40 }),
    paragraph('Recorded at: {!Release.VerifiedAt}', { after: 140 }),
    paragraph('Deterministic control results', { bold: true, size: 24, color: '102A43', before: 100, after: 80 }),
    paragraph('Controls recorded in this authorization: {!$count(Release.Checks)}', { bold: true, after: 80 }),
    paragraph('<mdoc:repeater name="verification-checks" value="Release.Checks" variable="check">', { after: 20 }),
    paragraph('• #check.Code# — #check.Outcome# — #check.Summary#', { after: 40 }),
    paragraph('</mdoc:repeater>', { after: 140 }),
    paragraph('Release boundary', { bold: true, size: 24, color: '102A43', before: 100, after: 80 }),
    paragraph('This document records an approved release packet. It does not execute payment and it is not self-signed by the agent. Foxit eSign sends this packet to a human signer, and VeriRemit accepts completion only from the authoritative Foxit status API.', { after: 180 }),
    paragraph('Generated from structured, auditable case data.', { size: 16, color: '627D98', align: 'center', before: 100, after: 0 }),
    '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="900" w:bottom="720" w:left="900" w:header="360" w:footer="360" w:gutter="0"/></w:sectPr>',
  ].join('');
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}</w:body></w:document>`;
}

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;
const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;

export function createDoctavianReleaseTemplate(): Uint8Array {
  return createStoredZip([
    { name: '[Content_Types].xml', bytes: encoder.encode(CONTENT_TYPES) },
    { name: '_rels/.rels', bytes: encoder.encode(ROOT_RELS) },
    { name: 'word/document.xml', bytes: encoder.encode(documentXml()) },
  ]);
}
