import {
  AlignmentType,
  BorderStyle,
  Document,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  type IBorderOptions,
} from 'docx';

interface ParagraphOptions {
  bold?: boolean;
  size?: number;
  color?: string;
  align?: 'center' | 'left';
  before?: number;
  after?: number;
}

const BORDER_COLOR = 'BCCCDC';
const INSIDE_BORDER_COLOR = 'D9E2EC';

function paragraph(text: string, options: ParagraphOptions = {}): Paragraph {
  return new Paragraph({
    alignment: options.align === 'center' ? AlignmentType.CENTER : AlignmentType.LEFT,
    spacing: {
      before: options.before ?? 0,
      after: options.after ?? 0,
    },
    children: [
      new TextRun({
        text,
        ...(options.bold ? { bold: true } : {}),
        ...(options.size !== undefined ? { size: options.size } : {}),
        ...(options.color !== undefined ? { color: options.color } : {}),
      }),
    ],
  });
}

function summaryRow(label: string, value: string): TableRow {
  return new TableRow({
    children: [
      new TableCell({
        width: { size: 2_200, type: WidthType.DXA },
        children: [paragraph(label, { bold: true, color: '243B53', after: 30 })],
      }),
      new TableCell({
        width: { size: 6_800, type: WidthType.DXA },
        children: [paragraph(value, { after: 30 })],
      }),
    ],
  });
}

function border(color: string): IBorderOptions {
  return { style: BorderStyle.SINGLE, size: 4, color };
}

function summaryTable(): Table {
  return new Table({
    width: { size: 9_000, type: WidthType.DXA },
    columnWidths: [2_200, 6_800],
    borders: {
      top: border(BORDER_COLOR),
      left: border(BORDER_COLOR),
      bottom: border(BORDER_COLOR),
      right: border(BORDER_COLOR),
      insideHorizontal: border(INSIDE_BORDER_COLOR),
      insideVertical: border(INSIDE_BORDER_COLOR),
    },
    rows: [
      summaryRow('Case', '{!Release.CaseId}'),
      summaryRow('Supplier', '{!Release.Supplier}'),
      summaryRow('Vendor ID', '{!Release.VendorId}'),
      summaryRow('Purchase order', '{!Release.PoNumber}'),
      summaryRow('Amount', '{!Release.Amount} {!Release.Currency}'),
      summaryRow('Beneficiary', '{!Release.Beneficiary}'),
      summaryRow('Verified IBAN', '{!Release.Iban}'),
    ],
  });
}

function releaseTemplateDocument(): Document {
  return new Document({
    creator: 'VeriRemit',
    lastModifiedBy: 'VeriRemit',
    title: 'VeriRemit Payment Release Authorization',
    subject: 'Human-verified vendor payment release',
    description: 'Doctavian template generated from structured VeriRemit case data.',
    sections: [
      {
        properties: {
          page: {
            size: { width: 12_240, height: 15_840 },
            margin: {
              top: 720,
              right: 900,
              bottom: 720,
              left: 900,
              header: 360,
              footer: 360,
              gutter: 0,
            },
          },
        },
        children: [
          paragraph('VERIREMIT', { bold: true, size: 36, color: '102A43', align: 'center', after: 60 }),
          paragraph('Payment Release Authorization', { bold: true, size: 28, align: 'center', after: 40 }),
          paragraph('Human-verified vendor payment change · generated by Doctavian', {
            size: 18,
            color: '486581',
            align: 'center',
            after: 220,
          }),
          summaryTable(),
          paragraph('Independent human verification', {
            bold: true,
            size: 24,
            color: '102A43',
            before: 240,
            after: 80,
          }),
          paragraph('Reviewer: {!Release.ReviewerName}', { after: 40 }),
          paragraph('Reference: {!Release.VerificationReference}', { after: 40 }),
          paragraph('Recorded at: {!Release.VerifiedAt}', { after: 140 }),
          paragraph('Deterministic control results', {
            bold: true,
            size: 24,
            color: '102A43',
            before: 100,
            after: 80,
          }),
          paragraph('Controls recorded in this authorization: {!$count(Release.Checks)}', {
            bold: true,
            after: 80,
          }),
          paragraph(
            '<mdoc:repeater name="verification-checks" value="{!Release.Checks}" variable="check" mode="standard">',
            { after: 20 },
          ),
          paragraph('• {!#check#.Code} — {!#check#.Outcome} — {!#check#.Summary}', { after: 40 }),
          paragraph('</mdoc:repeater name="verification-checks">', { after: 140 }),
          paragraph('Release boundary', {
            bold: true,
            size: 24,
            color: '102A43',
            before: 100,
            after: 80,
          }),
          paragraph(
            'This document records an approved release packet. It does not execute payment and it is not self-signed by the agent. Foxit eSign sends this packet to a human signer, and VeriRemit accepts completion only from the authoritative Foxit status API.',
            { after: 180 },
          ),
          paragraph('Generated from structured, auditable case data.', {
            size: 16,
            color: '627D98',
            align: 'center',
            before: 100,
          }),
        ],
      },
    ],
  });
}

const templateBytes = new Uint8Array(await Packer.toBuffer(releaseTemplateDocument()));

export function createDoctavianReleaseTemplate(): Uint8Array {
  return new Uint8Array(templateBytes);
}
